name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
      - name: check
        run: moon check --deny-warn
      - name: format
        run: moon fmt --check
